removed DotNetNuke.Web.Deprecated
DNNCommunity/DNN.Newsletter pull request #30
Opened 2021-01-18 23:42 UTC by gncube

### Removal of Telerik

## Changes made
- Telerik removed 

## PR Template Checklist
- [ ] Telerik removal 

## Please mark which issue is solved

Close #

2021-01-18 23:48 UTC, valadas commented on Dnn.Modules.Newsletters.csproj
> -    <Compile Include="Properties\AssemblyInfo.cs" />
Was this intentaional ?
the rest looks right to me.

2021-01-19 00:00 UTC, david-poindexter requested changes
This looks great @gncube - thanks so much for the contribution! 

With incrementing the version, I believe we also need to increment in the following places as well:
* https://github.com/DNNCommunity/DNN.Newsletter/blob/master/Properties/AssemblyInfo.cs#L36-L37
* https://github.com/DNNCommunity/DNN.Newsletter/blob/d5a6685be68e44b307d11c5bad15f6ddbe39d360/releaseNotes.txt

2021-01-19 00:00 UTC, david-poindexter commented on Dnn.Modules.Newsletters.csproj
> -    <Compile Include="Properties\AssemblyInfo.cs" />
@valadas these lines are still in the file (see https://github.com/DNNCommunity/DNN.Newsletter/pull/30/files#diff-6cc25bcd8a5814ee68133c156f31b2878515fa71bfbfcc32142242cd80a5bffeR106-R109) so I think this is fine.

2021-01-19 00:00 UTC, david-poindexter commented on dnn_Newsletters.dnn
> +    <package name="DotNetNuke.Newsletters" type="Module" version="08.01.01">
```suggestion
    <package name="DotNetNuke.Newsletters" type="Module" version="08.02.00">
```

I believe this warrants a minor release.

2021-01-19 00:19 UTC, valadas commented on Dnn.Modules.Newsletters.csproj
> -    <Compile Include="Properties\AssemblyInfo.cs" />
Oh, sorry, did not notice this 😄

2021-05-11 07:20 UTC, aspelt approved these changes
Good work!

2021-07-05 18:49 UTC, closed without merging